#!/bin/bash

#
# Copyright (c) 2021, MangDang Technology Co., Limited
#

#Power monitor
while true
do
	current_voltage=`python -c "from MangDang.mini_pupper.ESP32Interface import ESP32Interface;  print(int(ESP32Interface().get_power_status()['volt']*100))"`
	# Servos will be disabled by ESP32 when power is low
	if [ $current_voltage -le 620 ]; then
		# install scrip will replace BASEDIR
		mpg123 BASEDIR/Audio/low_power.mp3
	fi
	sleep 8
done
